[build]
  command = "npm start"  # Projeyi başlatmak için kullanılacak komut
  publish = "public"      # Derlenen dosyaların bulunduğu dizin

[dev]
  command = "npm start"   # Geliştirme sunucusunu başlatmak için kullanılacak komut
  publish = "public"      # Geliştirme sunucusunun yayınladığı dizin

[[redirects]]
  from = "/*"             # Tüm isteklerin
  to = "/index.html"      # index.html'e yönlendirilmesi
  status = 200            # 200 (OK) durum koduyla
